name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

  pull_request:
    branches:
      - master
    paths:
      - 'Formula/**/*.rb'

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_ANALYTICS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1
  HOMEBREW_GITHUB_PACKAGES_URL: "https://ghcr.io/v2/fnstruct/tap"

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - macos-13
          - macos-14
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Homebrew
        id: homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v4
        with:
          path: ${{ steps.homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-rubygems-${{ steps.homebrew.outputs.gems-hash }}
          restore-keys: |
            ${{ matrix.os }}-rubygems-

      - name: Check only-cleanup-before
        run: brew test-bot --only-cleanup-before

      - name: Check tap setup
        run: brew test-bot --only-setup

      - name: Check tap syntax
        run: brew test-bot --only-tap-syntax

      - name: Build bottles
        if: |
          github.event_name == 'pull_request'
          && !contains(github.event.pull_request.labels.*.name, 'lgtm')
        run: |
          brew test-bot --only-formulae --only-json-tab --root-url="$HOMEBREW_GITHUB_PACKAGES_URL"

      - name: Upload bottle artifacts
        if: |
          github.event_name == 'pull_request'
          && !contains(github.event.pull_request.labels.*.name, 'lgtm')
        uses: actions/upload-artifact@v4
        with:
          name: bottles_${{ matrix.os }}
          path: "*.bottle.*"

  publish-bottles:
    name: Publish bottles
    needs: build
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request'
      && !contains(github.event.pull_request.labels.*.name, 'lgtm')
    permissions:
      actions: read
      contents: write
      packages: write
      pull-requests: write
      attestations: write
      id-token: write
    env:
      PR: ${{ github.event.pull_request.number }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master

      - name: Checkout pull request branch
        run: |
          gh pr checkout "$PR" --repo "$GITHUB_REPOSITORY"

      - name: Download bottles from GitHub Actions
        uses: actions/download-artifact@v4
        with:
          pattern: bottles_*
          path: "${{ github.workspace }}/bottles"
          merge-multiple: true

      - name: Generate build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "${{ github.workspace }}/bottles/*.tar.gz"

      - name: Upload bottles to GitHub Packages
        env:
          HOMEBREW_GITHUB_PACKAGES_USER: fnstruct
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: "${{ github.workspace }}/bottles"
        run: brew pr-upload --debug --keep-old --root-url="$HOMEBREW_GITHUB_PACKAGES_URL"

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.pull_request.head.ref }}
          remote: ${{ github.event.pull_request.head.repo.clone_url }}
          remote_branch: ${{ github.event.pull_request.head.ref }}

      - name: Mark pull request as ready
        run: |
          gh pr edit --add-label "lgtm" "$PR" --repo "$GITHUB_REPOSITORY"
